title: AI & Life Science Blog
description: 조태호 교수의 AI 연구 블로그
author: 조태호
email: taehjo@gmail.com

theme: just-the-docs
url: https://taehojo.github.io

# No logo
logo: false

# Search disabled
search_enabled: false

# Navigation
nav_enabled: true

# No heading anchors
heading_anchors: false

# No back to top
back_to_top: false

# No footer
footer_content: ""

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-readme-index

readme_index:
  with_frontmatter: true

# Google Analytics
ga_tracking: UA-204303332-1
