title: 딥러닝과 생명과학
author: 조태호
email: taehjo@gmail.com
description: Deep learning Study, Deep learning in Science, Alphafold study

#theme: minima
remote_theme: just-the-docs/just-the-docs

readme_index:
  with_frontmatter: true
  
plugins:
  - github-pages

# Google Analytics
google_analytics: UA-204303332-1
